### ISSUE TITLE
Snooze timer

### ISSUE THREAD

**Issue by talandsouza** [suhasa010/simpletimer-telegram-bot#9]
Request for adding snooze button option to timer.
Example: 
/5
Snooze = remaining time + 10m.  

Or

When you click snooze button, it can give further buttons to choose the timer.
For example, if there are timer a, b, c, d, e

If i click snooze, it will give me 5 buttons to choose from.

**Comment by suhasa010** [comment]
Thank you. i will work on it.

**Comment by suhasa010** [comment]
done. by default snooze button will increase the timer by 10minutes. can click more times to increase for more duration. looking for a better implementation to increase for other times as well, like 20mins, 30 mins etc.
